arch : amd64
os: linux
dist: xenial

language: shell

addons:
  hosts:
    - pebble
    - pebble-challtestsrv
    - le1.wtf
    - le2.wtf
    - le3.wtf

env:
  global:
    - IMAGE=jrcs/letsencrypt-nginx-proxy-companion
    - NGINX_CONTAINER_NAME=nginx-proxy
    - DOCKER_GEN_CONTAINER_NAME=nginx-proxy-gen
    - TEST_DOMAINS=le1.wtf,le2.wtf,le3.wtf
    - DOCKER_COMPOSE_VERSION=1.24.0

jobs:
  include:
    - env: SETUP=2containers
    - env: SETUP=3containers
    - dist: bionic
      env: SETUP=2containers
    - dist: bionic
      env: SETUP=3containers
    - arch: arm64
      env: SETUP=2containers
    - arch: arm64
      env: SETUP=3containers
    - arch: arm64
      dist: bionic
      env: SETUP=2containers
    - arch: arm64
      dist: bionic
      env: SETUP=3containers

install:
  - docker build --force-rm --tag "$IMAGE" .
  - docker inspect "$IMAGE"
  - docker run --rm "$IMAGE" simp_le --version
  - docker run --rm "$IMAGE" simp_le --verbose --test
  - docker images

before_script:
  - git clone https://github.com/docker-library/official-images.git official-images
  - test/setup/setup-pebble.sh
  - test/setup/setup-nginx-proxy.sh
  - docker pull nginx:alpine

script:
  - official-images/test/run.sh "$IMAGE"
  - test/run.sh "$IMAGE"

after_failure:
  - test/travis/containers-logs.sh
